export const ROUTE = {
  home: {
    locale: 'home-page',
    path: 'home',
    fullPath: '/',
    name: 'Home Page',
  },
  about: {
    locale: 'about-page',
    path: 'about',
    fullPath: '/about/',
    name: 'About Page',
  },
  blog: {
    locale: 'blog-page',
    path: 'blog',
    fullPath: '/blogs/',
    name: 'Blog Page',
  },
  project: {
    locale: 'project-page',
    path: 'project',
    fullPath: '/projects/',
    name: 'Project Page',
  },
  login: {
    locale: 'login-page',
    path: 'login',
    fullPath: '/login/',
    name: 'Login Page',
  },
  admin: {
    locale: 'admin-page',
    path: 'admin',
    fullPath: '/admin/',
    name: 'Admin Page',
    icon: 'shield_person',
    main: {
      keys: ['admin', 'dashboard'],
      locale: 'admin-page.main-dashboard',
      path: 'dashboard',
      fullPath: '/admin/dashboard/',
      name: 'Dashboard Page',
      icon: 'dashboard',
      description: 'Dashboard page for admin',
    },
    certificate: {
      keys: ['admin', 'certificate'],
      locale: 'admin-page.certificate',
      path: 'certificate',
      fullPath: '/admin/certificate/',
      name: 'Certificate Page',
      icon: 'dataset',
      description: 'Certificate page for admin',
    },
    blog: {
      keys: ['admin', 'blog'],
      locale: 'admin-page.blog',
      path: 'blog',
      fullPath: '/admin/blog/',
      name: 'Blog Page',
      icon: 'article',
      description: 'Blog page for admin',
    },
    projectCategory: {
      keys: ['admin', 'project-category'],
      locale: 'admin-page.project-category',
      fullPath: '/admin/project-category/',
      name: 'Project Category Page',
      icon: 'category',
      description: 'Project Category page for admin',
    },
    project: {
      keys: ['admin', 'project'],
      locale: 'admin-page.project',
      path: 'project',
      fullPath: '/admin/project/',
      name: 'Project Page',
      icon: 'view_module',
      description: 'Project page for admin',
    },

  }
}